
package br.com.correios.logisticareversa;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "logisticaReversaWS", targetNamespace = "http://service.logisticareversa.correios.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogisticaReversaWS {


    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param coletasSolicitadas
     * @param codigoServico
     * @param destinatario
     * @return
     *     returns br.com.correios.logisticareversa.RetornoPostagem
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "solicitarPostagemReversa", targetNamespace = "")
    @RequestWrapper(localName = "solicitarPostagemReversa", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SolicitarPostagemReversa")
    @ResponseWrapper(localName = "solicitarPostagemReversaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SolicitarPostagemReversaResponse")
    public RetornoPostagem solicitarPostagemReversa(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "destinatario", targetNamespace = "")
        Destinatario destinatario,
        @WebParam(name = "coletas_solicitadas", targetNamespace = "")
        List<ColetaReversa> coletasSolicitadas)
        throws ComponenteException
    ;

    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param codigoServico
     * @param cepDestinatario
     * @param coleta
     * @return
     *     returns br.com.correios.logisticareversa.RetornoValidacao
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "validarPostagemSimultanea", targetNamespace = "")
    @RequestWrapper(localName = "validarPostagemSimultanea", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.ValidarPostagemSimultanea")
    @ResponseWrapper(localName = "validarPostagemSimultaneaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.ValidarPostagemSimultaneaResponse")
    public RetornoValidacao validarPostagemSimultanea(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "cep_destinatario", targetNamespace = "")
        String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        ColetaSimultanea coleta)
        throws ComponenteException
    ;

    /**
     * 
     * @param tipo
     * @param codAdministrativo
     * @param numeroPedido
     * @return
     *     returns br.com.correios.logisticareversa.RetornoCancelamento
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "cancelarPedido", targetNamespace = "")
    @RequestWrapper(localName = "cancelarPedido", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.CancelarPedido")
    @ResponseWrapper(localName = "cancelarPedidoResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.CancelarPedidoResponse")
    public RetornoCancelamento cancelarPedido(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "numeroPedido", targetNamespace = "")
        String numeroPedido,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo)
        throws ComponenteException
    ;

    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param coletasSolicitadas
     * @param codigoServico
     * @param destinatario
     * @return
     *     returns br.com.correios.logisticareversa.RetornoPostagem
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "solicitarPostagemSimultanea", targetNamespace = "")
    @RequestWrapper(localName = "solicitarPostagemSimultanea", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SolicitarPostagemSimultanea")
    @ResponseWrapper(localName = "solicitarPostagemSimultaneaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SolicitarPostagemSimultaneaResponse")
    public RetornoPostagem solicitarPostagemSimultanea(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "destinatario", targetNamespace = "")
        Destinatario destinatario,
        @WebParam(name = "coletas_solicitadas", targetNamespace = "")
        List<ColetaSimultanea> coletasSolicitadas)
        throws ComponenteException
    ;

    /**
     * 
     * @param tipo
     * @param codAdministrativo
     * @param servico
     * @param quantidade
     * @return
     *     returns br.com.correios.logisticareversa.RetornoFaixaNumerica
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "solicitarRange", targetNamespace = "")
    @RequestWrapper(localName = "solicitarRange", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SolicitarRange")
    @ResponseWrapper(localName = "solicitarRangeResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SolicitarRangeResponse")
    public RetornoFaixaNumerica solicitarRange(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "servico", targetNamespace = "")
        String servico,
        @WebParam(name = "quantidade", targetNamespace = "")
        String quantidade)
        throws ComponenteException
    ;

    /**
     * 
     * @param codAdministrativo
     * @param data
     * @param tipoSolicitacao
     * @return
     *     returns br.com.correios.logisticareversa.RetornoAcompanhamento
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "acompanharPedidoPorData", targetNamespace = "")
    @RequestWrapper(localName = "acompanharPedidoPorData", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.AcompanharPedidoPorData")
    @ResponseWrapper(localName = "acompanharPedidoPorDataResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.AcompanharPedidoPorDataResponse")
    public RetornoAcompanhamento acompanharPedidoPorData(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "tipoSolicitacao", targetNamespace = "")
        String tipoSolicitacao,
        @WebParam(name = "data", targetNamespace = "")
        String data)
        throws ComponenteException
    ;

    /**
     * 
     * @param codigoObjeto
     * @return
     *     returns br.com.correios.logisticareversa.RetornoResumoColeta
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "consultarResumoColeta", targetNamespace = "")
    @RequestWrapper(localName = "consultarResumoColeta", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.ConsultarResumoColeta")
    @ResponseWrapper(localName = "consultarResumoColetaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.ConsultarResumoColetaResponse")
    public RetornoResumoColeta consultarResumoColeta(
        @WebParam(name = "codigoObjeto", targetNamespace = "")
        String codigoObjeto)
        throws ComponenteException
    ;

    /**
     * 
     * @param tipoBusca
     * @param codAdministrativo
     * @param tipoSolicitacao
     * @param numeroPedido
     * @return
     *     returns br.com.correios.logisticareversa.RetornoAcompanhamento
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "acompanharPedido", targetNamespace = "")
    @RequestWrapper(localName = "acompanharPedido", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.AcompanharPedido")
    @ResponseWrapper(localName = "acompanharPedidoResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.AcompanharPedidoResponse")
    public RetornoAcompanhamento acompanharPedido(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "tipoBusca", targetNamespace = "")
        String tipoBusca,
        @WebParam(name = "tipoSolicitacao", targetNamespace = "")
        String tipoSolicitacao,
        @WebParam(name = "numeroPedido", targetNamespace = "")
        List<String> numeroPedido)
        throws ComponenteException
    ;

    /**
     * 
     * @param codAdministrativo
     * @param qtdeDias
     * @param numeroPedido
     * @return
     *     returns br.com.correios.logisticareversa.RetornoRevalidarPrazo
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "revalidarPrazoAutorizacaoPostagem", targetNamespace = "")
    @RequestWrapper(localName = "revalidarPrazoAutorizacaoPostagem", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.RevalidarPrazoAutorizacaoPostagem")
    @ResponseWrapper(localName = "revalidarPrazoAutorizacaoPostagemResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.RevalidarPrazoAutorizacaoPostagemResponse")
    public RetornoRevalidarPrazo revalidarPrazoAutorizacaoPostagem(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "numeroPedido", targetNamespace = "")
        String numeroPedido,
        @WebParam(name = "qtdeDias", targetNamespace = "")
        String qtdeDias)
        throws ComponenteException
    ;

    /**
     * 
     * @return
     *     returns br.com.correios.logisticareversa.RetornoSobreWebService
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "sobreWebService", targetNamespace = "")
    @RequestWrapper(localName = "sobreWebService", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SobreWebService")
    @ResponseWrapper(localName = "sobreWebServiceResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.SobreWebServiceResponse")
    public RetornoSobreWebService sobreWebService()
        throws ComponenteException
    ;

    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param codigoServico
     * @param cepDestinatario
     * @param coleta
     * @return
     *     returns br.com.correios.logisticareversa.RetornoValidacao
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "validarPostagemReversa", targetNamespace = "")
    @RequestWrapper(localName = "validarPostagemReversa", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.ValidarPostagemReversa")
    @ResponseWrapper(localName = "validarPostagemReversaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.ValidarPostagemReversaResponse")
    public RetornoValidacao validarPostagemReversa(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "cep_destinatario", targetNamespace = "")
        String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        ColetaReversa coleta)
        throws ComponenteException
    ;

    /**
     * 
     * @param numero
     * @return
     *     returns br.com.correios.logisticareversa.RetornoDigitoVerificador
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "calcularDigitoVerificador", targetNamespace = "")
    @RequestWrapper(localName = "calcularDigitoVerificador", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.CalcularDigitoVerificador")
    @ResponseWrapper(localName = "calcularDigitoVerificadorResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.correios.logisticareversa.CalcularDigitoVerificadorResponse")
    public RetornoDigitoVerificador calcularDigitoVerificador(
        @WebParam(name = "numero", targetNamespace = "")
        String numero)
        throws ComponenteException
    ;

}
